language: android
jdk: oraclejdk7
android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-23.0.2 # 23.0.2 was not available on build
    - build-tools-23.0.1
    - build-tools-23.0.3
    - build-tools-19.1.0
    # The SDK version used to compile your project
    - android-23
    - android-22
    - android-21
    - android-19
    - android-18
    - android-15
    - android-10
    - android-8
    - addon-google_apis-google-10
    - addon-google_apis-google-15
    - addon-google_apis-google-18
    - addon-google_apis-google-19
    - addon-google_apis-google-21
    - addon-google_apis-google-22
    - addon-google_apis-google-23
    - addon-google_apis-google-8

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-android-8
    - sys-img-armeabi-android-10
    - sys-img-armeabi-android-15
    - sys-img-armeabi-android-19
    - sys-img-armeabi-android-21
    - sys-img-x86-android-22
    - sys-img-x86-android-23
    - addon-google_apis-google-23

sudo: required

# fun fact, travis doesn't really support multiple AVDs running currently for a single build (tried it, build timed out constantly while starting up the AVDs)
# thus we're using a build matrix (which makes more sense anyhow)
env:
    global:
    #minutes (2 minutes by default), prevents CommandShellUnresponsiveExceptions
    - ADB_INSTALL_TIMEOUT=14

    matrix:
    #note when changing these, updating the gradle build file for the GoogleWrapper project
    # first env var is just for display purposes
    #api15 with google
    - API=15g ANDROID_TARGET=14  ANDROID_ABI=armeabi-v7a

before_install:
  # create and start emulators
  - android list targets
  - echo no | android create avd --force -n test$ANDROID_TARGET -t $ANDROID_TARGET --abi $ANDROID_ABI --sdcard 200M
  - emulator -memory 1536 -avd test$ANDROID_TARGET -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

# mvn sdk deploy
before_script:

  - android-wait-for-emulator
  - adb shell input keyevent 82 &

#build
script:
  - ./gradlew -version
  - ./gradlew connectedCheck
  # FIXME one day add in -Pprofile=ci to the above line
  # removed for now because travis will abort the build because the logout is too high

after_failure:
  # run this on failure
  # dumps the log then exits
  - adb logcat -d